// The 22 patterns from Oxford ceiling, in isolation.
window.LIBRARY = [
  { slug: "editorial-metadata-rail", title: "Editorial metadata rail", scale: "systemizable", mobileSafe: true, voice: "all (chrome)", pages: "Home, About, Services, Process, Gallery, Reviews, Contact",
    rationale: "Sticky left-column meta. File number, voice tag, subject, GPS, license. Turns 'about this page' into 'about this file'. The single biggest structural gap vs F3/F5/F6.",
    replaces: "Replaces the generic opening kicker / eyebrow used on every flagship page.",
    mobile: "Collapses to a horizontal row above content. Borders rotate from left-side to top-side. Fully ports.",
    path: "Already systemizable. Pulls from site config + GMB + voice config." },

  { slug: "stat-row-editorial", title: "Four-number editorial stat row", scale: "systemizable", mobileSafe: true, voice: null, pages: "Home hero, Reviews, About",
    rationale: "Display-serif numerals with mono labels. Years / reviews / rating / area. Replaces generic 'about us' blurb with falsifiable claims.",
    replaces: "F6 has a stat strip but uses sans numerals with no typographic weight. Falls into SaaS convention.",
    mobile: "Grid stays as 4 columns; numerals scale down via clamp(). Below 420px, wraps to 2x2.",
    path: "Already systemizable. Pulls from GMB API + service-area JSON." },

  { slug: "voice-tagged-sections", title: "Voice-tagged sections (eyebrow system)", scale: "systemizable", mobileSafe: true, voice: "varies per section", pages: "Sitewide",
    rationale: "Every section eyebrow declares its voice. Enforces 'one section, one voice' and trains the reader to feel the shift.",
    replaces: "F3/F5/F6 use generic all-caps eyebrows with topical labels only. No voice signaling.",
    mobile: "No change. Eyebrow shrinks by one step at <600px.",
    path: "Already systemizable. Voice assignment per section becomes part of site config (voices.json)." },

  { slug: "service-area-ledger-dark", title: "Service-area ledger table (dark)", scale: "systemizable", mobileSafe: true, voice: "Saturday Morning", pages: "Home",
    rationale: "Editorial table on stone background. Columns are trade-config: lawn = town/county/grass/drive time. Plumber = town/county/response/emergency hours.",
    replaces: "F3/F5/F6 use pill/chip clouds of service areas. Visually flat, no hierarchy.",
    mobile: "Table goes to single-column cards below 640px. Each row becomes a card with label/value pairs.",
    path: "Already systemizable. Rows come from service-area JSON; columns from trade config." },

  { slug: "numbered-service-cards", title: "Numbered horizontal service cards", scale: "systemizable", mobileSafe: true, voice: "Closing Table", pages: "Services",
    rationale: "Large numeral block + title + description + right-column meta. Process default, degrades to un-numbered for broad-offering trades.",
    replaces: "F5's 19-service tile wall. Loses hierarchy immediately past 6 cards.",
    mobile: "Meta column drops below description. Numeral shrinks from 60px to 44px.",
    path: "Already systemizable. Step count / card count is a trade variable." },

  { slug: "interactive-process-stepper", title: "Interactive process stepper", scale: "systemizable", mobileSafe: false, voice: "Closing Table", pages: "Process",
    rationale: "Sticky left nav + animated right panel. Works for any sequenced trade: HVAC install, septic, pool remodel, electrical service upgrade.",
    replaces: "No equivalent on F3/F5/F6. They list services as siblings; we sequence.",
    mobile: "GATED · sticky-left pattern collapses to a horizontal chip bar with scroll-snap panels. Needs separate mobile build.",
    path: "Already systemizable at structure level. Mobile variant needs one-time component work." },

  { slug: "timeline-ledger-dark", title: "Editorial timeline ledger (dark)", scale: "systemizable", mobileSafe: true, voice: "Closing Table", pages: "About",
    rationale: "Year / event / why-it-mattered table on dark. Every contractor has a story; flagships don't tell one.",
    replaces: "F3/F6 have no timeline. F5 has a prose paragraph that mentions dates.",
    mobile: "Three columns collapse to stacked year-label headers with event + why as a paragraph beneath.",
    path: "Already systemizable. Populated at onboarding voice interview (5–10 min client call)." },

  { slug: "trust-band-marquee", title: "Saturday Morning trust band marquee", scale: "systemizable", mobileSafe: true, voice: "Saturday Morning", pages: "Home",
    rationale: "Infinite-scroll trust phrases on accent-colored band. Phrase list tagged to trade in voice config. Replaces logo bars contractors can't fill.",
    replaces: "F3/F5 have placeholder logo strips. F6 has no equivalent.",
    mobile: "Scroll speed unchanged; font steps down one size. Works natively on narrow.",
    path: "Already systemizable. Voice skill generates phrases per trade." },

  { slug: "counter-list-what-we-dont-do", title: "Counter-list · what we don't do", scale: "systemizable", mobileSafe: true, voice: "Closing Table", pages: "Services",
    rationale: "Dark panel listing declined services. Reframes refusal as positioning. Differentiates specialists from broad offerings.",
    replaces: "No equivalent on F3/F5/F6. Standard contractor site lists everything plus 'and more'.",
    mobile: "Two-column split (heading / table) stacks. Table rows keep two columns.",
    path: "Section systemizable. Content requires voice-interview pass. Skip section if client's answers are weak." },

  { slug: "review-masonry-rhythm", title: "Masonry review wall with rhythm", scale: "systemizable", mobileSafe: true, voice: null, pages: "Home peek, Reviews",
    rationale: "Column-flow masonry with 3-pattern rhythm (normal / feature / dark). Pulls directly from Google Places API. Handles any review count.",
    replaces: "F3/F5/F6 use fixed 3-up or 6-up card grids that feel thin past 6 reviews.",
    mobile: "Column-count drops 3 → 2 → 1 at standard breakpoints. Pattern rhythm survives.",
    path: "Already systemizable. Live feed from Places API." },

  { slug: "before-after-slider", title: "Before/after compare slider", scale: "systemizable", mobileSafe: true, voice: null, pages: "Gallery",
    rationale: "Drag-handle split. Strong for lawn rehab, pool resurfacing, electrical panel, landscape installs. Weak for HVAC/plumbing — flag as trade-conditional.",
    replaces: "No equivalent on F3/F5/F6.",
    mobile: "Touch events already wired. Handle grows to 48px on touch. No layout change needed.",
    path: "Systemizable for ~30 of 50 trades. Gate per trade-config flag." },

  { slug: "filterable-gallery-tagged", title: "Filterable gallery with trade tags", scale: "systemizable", mobileSafe: true, voice: null, pages: "Gallery",
    rationale: "Masonry grid with location + process-stage filters. Tag schema swaps per trade.",
    replaces: "F3's plain grid gallery; F5's unfiltered tile wall.",
    mobile: "Filter row becomes horizontal-scroll chip bar. Grid collapses 12-col to 6-col to 3-col.",
    path: "Already systemizable. Tag schema per trade-config." },

  { slug: "chip-selector-form", title: "Chip-selector assessment form", scale: "systemizable", mobileSafe: true, voice: "Saturday Morning", pages: "Contact",
    rationale: "Chips for 'what do you need' map to services array. Grass-type dropdown becomes fixture-type / system for other trades.",
    replaces: "F3/F5/F6 use standard dropdown form. Chips increase tap targets and read friendlier on phone.",
    mobile: "Chip row wraps naturally. 44px tap targets. Form stacks to single column below 900px.",
    path: "Already systemizable. Trade config defines chip options + conditional fields." },

  { slug: "dropcap-editorial-prose", title: "Dropcap + editorial prose", scale: "systemizable", mobileSafe: true, voice: "varies", pages: "Home thesis, About",
    rationale: "Italic serif dropcap, 68ch measure, prose class. Turns contractor copy into feature-reading, not form fields.",
    replaces: "F3/F5/F6 use standard paragraph blocks at 80+ ch.",
    mobile: "Dropcap scales to 2.8em. Measure collapses to viewport width.",
    path: "Already systemizable. CSS class only." },

  { slug: "soil-strata-hero", title: "Soil-strata motif hero column", scale: "bespoke", mobileSafe: false, voice: null, pages: "Home, Process",
    rationale: "Stratified horizontal band (thatch / grass / root / compost / subsoil). Signature visual + divider + process diagram.",
    replaces: "The F6 7-photo crossfade hero.",
    mobile: "GATED · strata height is desktop-only. On mobile collapses to a compact strata chip rail above the fold.",
    path: "**BESPOKE · FIX: Vector asset library · stratified-band-motifs.** Build a reusable 'material cross-section' component with stratified-band variants per trade category: soil (lawn), water column (pool), earth profile (septic), structural assembly (roofing), panel assembly (electrical). Ships with ~10 trade variants. Moves from bespoke → systemizable for ~20 of 50 trades." },

  { slug: "serif-display-headline-system", title: "Serif-display editorial headline system", scale: "bespoke", mobileSafe: true, voice: null, pages: "Sitewide",
    rationale: "Newsreader with italic accents. Reads as trade-journal editorial. Lands for craft specialists. Lands wrong on 24-hour emergency plumbing.",
    replaces: "F3/F5/F6 use Space Grotesk/Inter — SaaS-safe, reads generic.",
    mobile: "Display steps down via clamp(). Italic accents survive. Ports cleanly.",
    path: "**BESPOKE · FIX: Trade-class variants.** Ship 3 typographic classes: editorial-specialist (Newsreader / JetBrains / Public Sans), operations-forward (Public Sans / Space Mono / Public Sans), emergency-urgent (Space Grotesk / Inter Tight / Inter). Tag each contractor at onboarding. Moves from bespoke → systemizable for all 50 trades." },

  { slug: "annotated-soil-cross-section", title: "Annotated soil cross-section", scale: "bespoke", mobileSafe: false, voice: "Closing Table", pages: "Process",
    rationale: "Tall strata panel + 'step 1 acts here / step 2 acts here' callouts. Labeled process diagram.",
    replaces: "F3/F5/F6 describe process in prose only.",
    mobile: "GATED · the side-by-side diagram + callouts stacks, which breaks the 'acts here →' arrow metaphor. Needs mobile diagram rework.",
    path: "**BESPOKE · FIX: Commissioned illustration pack.** Invest in ~15 annotated process diagrams (lawn soil, pool water column, septic drain field, HVAC ducting, electrical panel, plumbing riser, etc). Shared illustrator, shared style. One diagram per trade. Moves bespoke → systemizable for ~25 of 50 trades." },

  { slug: "pull-quote-founder", title: "Pull-quote with founder attribution", scale: "bespoke", mobileSafe: true, voice: "Front Porch", pages: "About",
    rationale: "Serif-italic pull quote with lawn-green left bar. Requires a founder who talks like their work.",
    replaces: "F3/F5/F6 have generic 'About Us' narrative without attributed voice.",
    mobile: "Left bar holds, quote reflows. Ports cleanly. Gate is content, not layout.",
    path: "**BESPOKE · FIX: Voice-interview onboarding gate.** Build a 10-minute founder voice-interview protocol (Claude-led, transcribed). If interview yields 3+ quotable lines, enable this pattern. If not, section is skipped. Pattern becomes 'systemizable when content exists' — systemizable for ~60% of clients." },

  { slug: "magazine-issue-chrome", title: "'Volume 18, Issue 1' editorial chrome", scale: "bespoke", mobileSafe: true, voice: null, pages: "Hero kicker, rails",
    rationale: "Magazine-issue metadata in the nav zone. Playful, editorial. Works for specialists with a story. May read gimmicky for storm-response trades.",
    replaces: "No equivalent on F3/F5/F6.",
    mobile: "Kicker row wraps. Last pieces drop at <600px via `.hide-mobile`.",
    path: "**BESPOKE · FIX: Paid-tier-only feature.** Ship on Premium-tier builds only. Ties to editorial-specialist typographic class. Paid-tier becomes the natural home for patterns that stretch past systemizable — gives us a price point for the ceiling." },

  { slug: "review-theme-index", title: "Review theme index (NLP-derived)", scale: "mixed", mobileSafe: true, voice: "Closing Table", pages: "Reviews",
    rationale: "'47 reviews mention on time / 34 mention straight answer.' Derived by Claude NLP pass at build time. Free for everyone once pipeline is built.",
    replaces: "No equivalent on F3/F5/F6.",
    mobile: "3-column grid stacks cleanly. No change.",
    path: "**MIXED · FIX: Build-time pipeline.** One-time Claude NLP ingest of every client's reviews at build. Extracts top 3 themes + counts. Once built, systemizable across all 50. Investment = ~1 day of Claude Code work on the ingest pipeline." },

  { slug: "photo-portraits-degrading", title: "Portrait / work-in-progress photo (degrading)", scale: "mixed", mobileSafe: true, voice: null, pages: "About, hero",
    rationale: "Tom + Tracy portraits ideal. Falls back to GMB truck-on-site → Instagram → placeholder. Photography sourcing systemizable; quality per client bespoke.",
    replaces: "F3/F5/F6 rely on stock or mixed quality.",
    mobile: "Photo slot aspect ratios maintained. Single-column stack.",
    path: "**MIXED · FIX: GMB + Instagram ingestion pipeline + fallback hierarchy.** Systemizable as a fetch strategy. Quality per client is data-driven not design-driven. Pattern ships; quality budgets go to photo-scarce clients individually." },

  { slug: "voice-tuned-counter-list", title: "Voice-tuned 'what we don't do' content", scale: "mixed", mobileSafe: true, voice: "Closing Table", pages: "Services",
    rationale: "Section is systemizable (see pattern 09). Content requires a client who can articulate what they decline and why.",
    replaces: "See pattern 09.",
    mobile: "See pattern 09.",
    path: "**MIXED · FIX: Voice-interview trigger.** Section auto-ships only if voice interview scores 3+ declinations. Systemizable at pipeline level, bespoke at content level. Same interview as pull-quote pattern — no extra onboarding cost." },
];
